version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Test
          command: npm run test
#      - run:
#          name: Test
#          command: npm run test:e2e
      - store_artifacts:
          path: test-results.xml
          prefix: tests
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - dist
            - docs
  push:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - attach_workspace:
          at:
            .
      - run:
          name: Git
          command: |
            git config user.email "formiobot@form.io"
            git config user.name "Formobot"
            git add -A && git commit -m "Build $CIRCLE_TAG"
            git push -u origin $CIRCLE_BRANCH
      - run:
          name: NPM
          command: |
            npm publish lib --tag 4x
            if [[ $CIRCLE_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              npm dist-tag formiojs@$CIRCLE_TAG latest
            fi

workflows:
  version: 2
  do-build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - push:
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
